mirar si

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -2,9 +2,6 @@ name: publish
 #Accion que inicia el flujo en este caso es la actualizacion a la rama main 
 on:
   push:
-    branches: ["feacture/Todo"]
-
-      pull_request: 
     branches: ["main"]
 
 #Flujo en este caso el flujo esta dividido en dos creacion del docker y luego el deploy 
@@ -28,10 +25,22 @@ jobs:
       - name: Build with Maven
         run: |
           cd "./Back end/App_gestion" 
-          #Este es el comando en cuestion
+          #Este es el comando en cuestion,
           mvn clean package
         #Los contenedores se pueden almacenar en github en el aprtado de packgaes este subpaso se logea en 
         #Los s contenedores 
+
+
+      - name: Check for .jar file
+        run: |
+          cd "./Back end/App_gestion"
+          if [ -f "./target/App_gestion-0.0.1-SNAPSHOT.jar" ]; then
+            echo "Jar file exists"
+          else
+            echo "Jar file not found. Aborting."
+            exit 1
+          fi
+
       - name: Login to s Container Register
         uses: docker/Login-action@v1
         with:
